main = ".open-next/worker.js"
name = "copilot"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "LIVEASSETS"

[[routes]]
pattern = "copilot.vedgupta.in"
custom_domain = true

[observability]
enabled = true